=== My-Student-Projects/XML-Project9/Playlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="playlist">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Music" minOccurs="3" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Artist" type="xs:string"/>
								    <xs:complexType>
										<xs:attribute name="genre" type="xs:string" use="required" />
									</xs:complexType>
							<xs:element name="Album" type="xs:string"/>
								    <xs:complexType>
										<xs:attribute name="year" type="xs:integer" use="required" />
									</xs:complexType>
							<xs:element name="Song" type="xs:string"/>
								    <xs:complexType>
										<xs:attribute name="length" type="xs:string" use="required" />
									</xs:complexType>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== My-Student-Projects/XML-Project9/Playlist.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="Playlist.xsl"?>
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema"
	xsi:noNamespaceSchemaLocation="Playlist.xsd">
<!-- RoxSeibert Web126 Course Project-->
	<Music genre="Classic Rock" year="1971" length="08:02">
		<Artist>Led Zeppelin</Artist>
		<Album>Led Zeppelin IV</Album>
		<Song>Stairway to Heaven</Song>
	</Music>
	<Music genre="Rockabilly" year="2004" length="02:54">
		<Artist>Sonny Burgess with The Blasters</Artist>
		<Album><![CDATA[The Blasters Live: Going Home]]></Album>
		<Song>Red Headed Woman</Song>
	</Music>
	<Music genre="Hard Rock" year="1968" length="03:30">
		<Artist>Steppenwolf</Artist>
		<Album>Steppenwolf</Album>
		<Song>Born to Be Wild</Song>
	</Music>
	<Music genre="Modern Rock" year="1978" length="03:12">
		<Artist>Police</Artist>
		<Album>Outlandos d&apos;Amour</Album>
		<Song>Roxanne</Song>
	</Music>
</playlist>
